/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.*;
import java.net.URL;

/**
 *
 * @author bea
 */


public class FrmLogin extends javax.swing.JFrame {
    
//    //Establecemos color de fondo
//        Color fondo= new Color(222, 237, 215 );
//        
    
    //Establecemos la ruta de la imagen que se va a poner de fondo
        String ruta_imagenFondo="../imagenes/montañas.png";
    
    //Instanciamos la clase de la imagen de fondo
        ImagenFondo fondo_login= new ImagenFondo(ruta_imagenFondo);
        
    /**
     * Creates new form FrmLogin
     */
    
     
    public FrmLogin() {
        
        //Se mete la imagen de fondo
        this.setContentPane(fondo_login);
       
        initComponents();
      
       //Cambiar icono de la barra (no se ve en linux pero si en windows
      this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/Logo.png")).getImage());
         
             //Centramos la ventana
        this.setLocationRelativeTo(null);

        
        //PARA CONECTAR LA BASE DE DATOS AL FORMULARIO
        int resultado = Conexion.conectar("localhost", "3306", "root", "BESTARRUZA", "FPDual2022");
        if (resultado == 0) {
            System.out.println("Conexión correcta con la base de datos");
//            JOptionPane.showMessageDialog(this, "Conexión OK"); Comentamos para que no salga el mensaje cuando cerramos sesión desde la app
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido conectar a la base de datos");
        }

        //IMAGEN USUARIO
            //Se instancia la imagen y se recoge dicha imagen de la ruta
                URL urlImagenUsuario = this.getClass().getResource("../imagenes/usuario.png");
                Image imagenUsuario = new ImageIcon(urlImagenUsuario).getImage();

            //Se pasa la imagen a icon y se eligen las dimensiones de dicha imagen
                ImageIcon iconUsuario = new ImageIcon(imagenUsuario.getScaledInstance(lblImagenUsuario.getWidth(), lblImagenUsuario.getHeight(), Image.SCALE_SMOOTH));

            //Se introduce la imagen dentro de la etiqueta
                lblImagenUsuario.setIcon(iconUsuario);

        //IMAGEN CONTRASEÑA
            //Se instancia la imagen y se recoge dicha imagen de la ruta
                URL urlImagenContraseña = this.getClass().getResource("../imagenes/contraseña.png");
                Image imagenContraseña = new ImageIcon(urlImagenContraseña).getImage();
                
            //Se pasa la imagen a icon y se eligen las dimensiones de dicha imagen       
                
                ImageIcon iconContraseña = new ImageIcon(imagenContraseña.getScaledInstance(lblImagenContraseña.getWidth(), lblImagenContraseña.getHeight(), Image.SCALE_SMOOTH));
            //Se introduce la imagen dentro de la etiqueta    
                lblImagenContraseña.setIcon(iconContraseña);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        pswContraseña = new javax.swing.JPasswordField();
        lblImagenUsuario = new javax.swing.JLabel();
        lblImagenContraseña = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BESTARRUZA");
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblUsuario.setText("USUARIO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 0);
        getContentPane().add(lblUsuario, gridBagConstraints);

        lblContraseña.setText("CONTRASEÑA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        getContentPane().add(lblContraseña, gridBagConstraints);

        btnIniciarSesion.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnIniciarSesion.setText("INICIAR SESIÓN");
        btnIniciarSesion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setMaximumSize(new java.awt.Dimension(109, 35));
        btnIniciarSesion.setMinimumSize(new java.awt.Dimension(109, 35));
        btnIniciarSesion.setPreferredSize(new java.awt.Dimension(109, 35));
        btnIniciarSesion.setRolloverEnabled(false);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 4, 70);
        getContentPane().add(btnIniciarSesion, gridBagConstraints);

        btnCancelar.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setMaximumSize(new java.awt.Dimension(109, 35));
        btnCancelar.setMinimumSize(new java.awt.Dimension(109, 35));
        btnCancelar.setPreferredSize(new java.awt.Dimension(109, 35));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(4, 20, 20, 70);
        getContentPane().add(btnCancelar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 10, 70);
        getContentPane().add(txtUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 70);
        getContentPane().add(pswContraseña, gridBagConstraints);

        lblImagenUsuario.setMaximumSize(new java.awt.Dimension(20, 25));
        lblImagenUsuario.setMinimumSize(new java.awt.Dimension(20, 25));
        lblImagenUsuario.setPreferredSize(new java.awt.Dimension(20, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 70, 4, 0);
        getContentPane().add(lblImagenUsuario, gridBagConstraints);

        lblImagenContraseña.setMaximumSize(new java.awt.Dimension(25, 25));
        lblImagenContraseña.setMinimumSize(new java.awt.Dimension(25, 25));
        lblImagenContraseña.setPreferredSize(new java.awt.Dimension(25, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 70, 0, 0);
        getContentPane().add(lblImagenContraseña, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
    //Recorremos la base de datos para comprobar si el usuario existe
        existeUsuario();
        
        
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void existeUsuario(){
        
        String usuario = txtUsuario.getText().trim();
        String contraseña = Encriptado.encriptar(pswContraseña.getText().trim());
        
        
        
        try {
            //Crear un statement. Statement significa que en la conexion que tengo abierta me cree una zona de trabajo 
            Statement stmt = Conexion.getConexion().createStatement();
            //Generamos la consulta como en SQL PARA UN SELECT
            String consulta = "SELECT USUARIO_APP, CONTRASEÑA FROM JUNTA_DIRECTIVA WHERE USUARIO_APP='"+usuario+"'";
            //Sacamos por pantalla la consulta para ver posibles errores
            System.out.println(consulta);
            //Para lanzar la consulta SELECT
            ResultSet rs = stmt.executeQuery(consulta);

            String user="";
            String password="";
            while (rs.next()) {
                 
                user = rs.getString(1); //rs.getInt devuelve un entero; hay que indicar el número de columna
                password = rs.getString(2); //rs.getString devuelve un String; hay que indicar el número de columna
               
            }
            
            if(usuario.equals(user) && contraseña.equals(password)){
                FrmPrincipal principal= new FrmPrincipal();
                principal.setVisible(true);
                
                 ((FrmPrincipal)getParent()).cambiarNombreUsuario(usuario);
        
        
                dispose();
            } else{
                JOptionPane.showMessageDialog(this, "Error. Usuario o contraseña incorrectos.");
            }

        } catch (SQLException e1) {
            e1.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error recuperando datos de usuario");

        }
        
        

    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       //Cierra la aplicación 
       System.exit(0);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblImagenContraseña;
    private javax.swing.JLabel lblImagenUsuario;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
