/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.Image;
import java.net.URL;
import javax.swing.Box;
import javax.swing.ImageIcon;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author bea
 */
public class FrmPrincipal extends javax.swing.JFrame {
 //Establecemos color de fondo
        Color fondo= new Color(222, 237, 215 );
        Socio socio=null;
        JuntaDirectiva juntaDirectiva=null;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        //Cambiar icono de la barra (no se ve en linux pero si en windows
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/Logo.png")).getImage());

        //Pinta el formulario
        this.getContentPane().setBackground(fondo);

                //Centramos la ventana
        this.setLocationRelativeTo(null);
        
        //Alinear a la derecha de la barra una opción de menú con sus items
        mnuBarPrincipal.add(Box.createHorizontalGlue());
        mnuBarPrincipal.add(mnuUsuario);
        mnuUsuario.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT); 
        
        
        //IMAGEN DE FONDO 
            //Se instancia la imagen y se recoge dicha imagen de la ruta
                URL urlImagenUsuario = this.getClass().getResource("../imagenes/Logo.png");
                Image imagenUsuario = new ImageIcon(urlImagenUsuario).getImage();

            //Se pasa la imagen a icon y se eligen las dimensiones de dicha imagen
                ImageIcon iconUsuario = new ImageIcon(imagenUsuario.getScaledInstance(lblLogo.getWidth(), lblLogo.getHeight(), Image.SCALE_SMOOTH));

            //Se introduce la imagen dentro de la etiqueta
                lblLogo.setIcon(iconUsuario);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblLogo = new javax.swing.JLabel();
        mnuBarPrincipal = new javax.swing.JMenuBar();
        mnuMaterial = new javax.swing.JMenu();
        jmnuiNuevoMaterial = new javax.swing.JMenuItem();
        jmnuiBuscadorMaterial = new javax.swing.JMenuItem();
        mnuPrestamos = new javax.swing.JMenu();
        jmnuiPrestamos = new javax.swing.JMenuItem();
        jmnuiDevoluciones = new javax.swing.JMenuItem();
        mnuSocios = new javax.swing.JMenu();
        mnuiNuevoSocio = new javax.swing.JMenuItem();
        mnuiBuscadorSocios = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();
        mnuiAyuda = new javax.swing.JMenuItem();
        mnuUsuario = new javax.swing.JMenu();
        mnuiMiCuenta = new javax.swing.JMenuItem();
        mnuiCerrarSesion = new javax.swing.JMenuItem();
        mnuiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU PRINCIPAL");
        setBackground(new java.awt.Color(222, 237, 215));
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblLogo.setMaximumSize(new java.awt.Dimension(400, 400));
        lblLogo.setMinimumSize(new java.awt.Dimension(400, 400));
        lblLogo.setPreferredSize(new java.awt.Dimension(400, 400));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(lblLogo, gridBagConstraints);

        mnuMaterial.setText("Material");

        jmnuiNuevoMaterial.setText("Nuevo");
        jmnuiNuevoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuiNuevoMaterialActionPerformed(evt);
            }
        });
        mnuMaterial.add(jmnuiNuevoMaterial);

        jmnuiBuscadorMaterial.setText("Buscador");
        jmnuiBuscadorMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuiBuscadorMaterialActionPerformed(evt);
            }
        });
        mnuMaterial.add(jmnuiBuscadorMaterial);

        mnuBarPrincipal.add(mnuMaterial);

        mnuPrestamos.setText("Préstamos");

        jmnuiPrestamos.setText("Préstamos");
        jmnuiPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuiPrestamosActionPerformed(evt);
            }
        });
        mnuPrestamos.add(jmnuiPrestamos);

        jmnuiDevoluciones.setText("Devoluciones");
        jmnuiDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnuiDevolucionesActionPerformed(evt);
            }
        });
        mnuPrestamos.add(jmnuiDevoluciones);

        mnuBarPrincipal.add(mnuPrestamos);

        mnuSocios.setText("Socios");

        mnuiNuevoSocio.setText("Nuevo");
        mnuiNuevoSocio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiNuevoSocioActionPerformed(evt);
            }
        });
        mnuSocios.add(mnuiNuevoSocio);

        mnuiBuscadorSocios.setText("Buscador");
        mnuiBuscadorSocios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiBuscadorSociosActionPerformed(evt);
            }
        });
        mnuSocios.add(mnuiBuscadorSocios);

        mnuBarPrincipal.add(mnuSocios);

        mnuAyuda.setText("Acerca de");

        mnuiAyuda.setText("Ayuda");
        mnuAyuda.add(mnuiAyuda);

        mnuBarPrincipal.add(mnuAyuda);

        mnuUsuario.setText("Usuario");

        mnuiMiCuenta.setText("Mi cuenta");
        mnuiMiCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiMiCuentaActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuiMiCuenta);

        mnuiCerrarSesion.setText("Cerrar sesión");
        mnuiCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiCerrarSesionActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuiCerrarSesion);

        mnuiSalir.setText("Salir");
        mnuiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuiSalirActionPerformed(evt);
            }
        });
        mnuUsuario.add(mnuiSalir);

        mnuBarPrincipal.add(mnuUsuario);

        setJMenuBar(mnuBarPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiSalirActionPerformed
        //Sale de la aplicacion 
        System.exit(0);
    }//GEN-LAST:event_mnuiSalirActionPerformed
    //Método para establecer el nombre del usuario en la parte derecha del menú, donde desplegando podremos ver las opciones de mi cuenta, cerrar sesion y salir.
    public static void cambiarNombreUsuario(String usuario){    
        mnuUsuario.setText(usuario.toUpperCase());
    }
    
    private void mnuiCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiCerrarSesionActionPerformed
        // Vuelve a la ventana de login
        dispose();
        FrmLogin login= new FrmLogin();
        login.setVisible(true);
        
    }//GEN-LAST:event_mnuiCerrarSesionActionPerformed

    private void jmnuiNuevoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuiNuevoMaterialActionPerformed
        // TODO add your handling code here:
        DlgNuevoMaterial nuevoMaterial = new DlgNuevoMaterial(this, false);
        nuevoMaterial.setVisible(true);
    }//GEN-LAST:event_jmnuiNuevoMaterialActionPerformed

    private void mnuiNuevoSocioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiNuevoSocioActionPerformed
        // TODO add your handling code here:
        DlgNuevoSocio nuevoSocio = new DlgNuevoSocio(this, false);
        nuevoSocio.setVisible(true);
    }//GEN-LAST:event_mnuiNuevoSocioActionPerformed

    private void jmnuiBuscadorMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuiBuscadorMaterialActionPerformed
        // TODO add your handling code here:
        DlgBuscadorMaterial buscadorMaterial = new DlgBuscadorMaterial(this, false);
        buscadorMaterial.setVisible(true);
    }//GEN-LAST:event_jmnuiBuscadorMaterialActionPerformed

    private void mnuiBuscadorSociosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiBuscadorSociosActionPerformed
        // TODO add your handling code here:
        DlgBuscadorSocio buscadorSocio = new DlgBuscadorSocio(this, false);
        buscadorSocio.setVisible(true);
    }//GEN-LAST:event_mnuiBuscadorSociosActionPerformed

    private void mnuiMiCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuiMiCuentaActionPerformed
        // TODO add your handling code here:
        usuarioAppMiCuenta();
        DlgMiCuenta miCuenta = new DlgMiCuenta(this, false, socio, juntaDirectiva);
        miCuenta.setVisible(true);
    }//GEN-LAST:event_mnuiMiCuentaActionPerformed

    private void usuarioAppMiCuenta(){
        try{
            Statement statement = Conexion.getConexion().createStatement();
            String consulta = "SELECT SOCIO.NUM_SOCIO, DNI, NOMBRE, APELLIDO, FECHA_NACIMIENTO, DIRECCION, TELEFONO, EMAIL, JUNTA_DIRECTIVA.USUARIO_APP, JUNTA_DIRECTIVA.CONTRASEÑA  FROM SOCIO LEFT JOIN JUNTA_DIRECTIVA ON SOCIO.NUM_SOCIO=JUNTA_DIRECTIVA.NUM_SOCIO WHERE USUARIO_APP='"+mnuUsuario.getText().trim()+"'";
            System.out.println(consulta);
            ResultSet resultSet = statement.executeQuery(consulta);

            while (resultSet.next()) {
                int num_socio = resultSet.getInt(1);
                String dni = resultSet.getString(2);
                String nombre = resultSet.getString(3);
                String apellido = resultSet.getString(4);
                String email = resultSet.getString(8);
                String fecha_nacimiento = resultSet.getString(5);
                int telefono = resultSet.getInt(7);
                String direccion = resultSet.getString(6);

                String usuario_app = resultSet.getString(9);
                String contraseña = resultSet.getString(10);

                //Creo socio y miembro de la junta directiva
                socio = new Socio(num_socio, dni, nombre, apellido, email, fecha_nacimiento, telefono, direccion);
                juntaDirectiva = new JuntaDirectiva(usuario_app, contraseña);
 
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }
    private void jmnuiPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuiPrestamosActionPerformed
        // TODO add your handling code here:
        DlgPrestamos prestamos = new DlgPrestamos(this, false);
        prestamos.setVisible(true);
    }//GEN-LAST:event_jmnuiPrestamosActionPerformed

    private void jmnuiDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnuiDevolucionesActionPerformed
        // TODO add your handling code here:
        DlgDevoluciones devoluciones = new DlgDevoluciones(this, false);
        devoluciones.setVisible(true);    }//GEN-LAST:event_jmnuiDevolucionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jmnuiBuscadorMaterial;
    private javax.swing.JMenuItem jmnuiDevoluciones;
    private javax.swing.JMenuItem jmnuiNuevoMaterial;
    private javax.swing.JMenuItem jmnuiPrestamos;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuBar mnuBarPrincipal;
    private javax.swing.JMenu mnuMaterial;
    private javax.swing.JMenu mnuPrestamos;
    private javax.swing.JMenu mnuSocios;
    public static javax.swing.JMenu mnuUsuario;
    private javax.swing.JMenuItem mnuiAyuda;
    private javax.swing.JMenuItem mnuiBuscadorSocios;
    private javax.swing.JMenuItem mnuiCerrarSesion;
    private javax.swing.JMenuItem mnuiMiCuenta;
    private javax.swing.JMenuItem mnuiNuevoSocio;
    private javax.swing.JMenuItem mnuiSalir;
    // End of variables declaration//GEN-END:variables
}
